import axios from 'axios';
const BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';
const api = axios.create({ baseURL: BASE });
api.interceptors.request.use((c) => {
  const t = localStorage.getItem('hr_token');
  if (t) c.headers.Authorization = 'Bearer ' + t;
  return c;
});
export const login = (email, password) => api.post('/auth/login', { email, password }).then(r => r.data);
export const getMe = () => api.get('/auth/me').then(r => r.data);
export const getDepartments = () => api.get('/departments').then(r => r.data);
export const getEmployees = (p) => api.get('/employees', { params: p }).then(r => r.data);
export const createEmployee = (d) => api.post('/employees', d).then(r => r.data);
export const updateEmployee = (id, d) => api.put('/employees/' + id, d).then(r => r.data);
export const deactivateEmployee = (id) => api.delete('/employees/' + id).then(r => r.data);
export const getAttendance = (p) => api.get('/attendance', { params: p }).then(r => r.data);
export const checkIn = () => api.post('/attendance/checkin').then(r => r.data);
export const checkOut = () => api.post('/attendance/checkout').then(r => r.data);
export const getAttendanceSummary = (id, m, y) => api.get('/attendance/summary/' + id, { params: { month: m, year: y } }).then(r => r.data);
export const getLeaves = (p) => api.get('/leaves', { params: p }).then(r => r.data);
export const applyLeave = (d) => api.post('/leaves', d).then(r => r.data);
export const approveLeave = (id, d) => api.put('/leaves/' + id + '/approve', d).then(r => r.data);
export const getHolidays = (y) => api.get('/holidays', { params: { year: y } }).then(r => r.data);
export const getPayroll = (p) => api.get('/payroll', { params: p }).then(r => r.data);
export const processPayroll = (d) => api.post('/payroll/process', d).then(r => r.data);
export const getPayslip = (id) => api.get('/payroll/' + id + '/payslip').then(r => r.data);
export const markPayrollPaid = (id) => api.put('/payroll/' + id + '/mark-paid').then(r => r.data);
export const getTaxDeclarations = () => api.get('/tax/declarations').then(r => r.data);
export const submitTaxDeclaration = (d) => api.post('/tax/declarations', d).then(r => r.data);
export const calculateTax = (p) => api.get('/tax/calculator', { params: p }).then(r => r.data);
export const getBenefitPlans = () => api.get('/benefits/plans').then(r => r.data);
export const getMyBenefits = () => api.get('/benefits/my').then(r => r.data);
export const getDashboardStats = () => api.get('/reports/dashboard').then(r => r.data);
export const getPayrollSummary = (m, y) => api.get('/reports/payroll-summary', { params: { month: m, year: y } }).then(r => r.data);
export const getHeadcountReport = () => api.get('/reports/headcount').then(r => r.data);
export const getAttendanceSummaryReport = (m, y) => api.get('/reports/attendance-summary', { params: { month: m, year: y } }).then(r => r.data);
export const getAnnouncements = () => api.get('/announcements').then(r => r.data);
export const sendChat = (d) => api.post('/chat', d).then(r => r.data);
export const getTickets = () => api.get('/tickets').then(r => r.data);
export const uploadPolicy = (file) => { const fd = new FormData(); fd.append('file', file); return api.post('/upload_policy', fd).then(r => r.data); };
export default api;
